import React, { useState } from 'react';
import Modal from './Modal.jsx';
import { artworks } from '../artworks.js';

const edits = [
  { category: 'Landscapes', title: 'A quieter kind of escape.', image: '/artworks/wheat-field.jpg', text: 'Open skies & faraway places' },
  { category: 'Seascapes', title: 'Follow the blue.', image: '/artworks/great-wave.jpg', text: 'Coastal light & moving water' },
  { category: 'Portraits', title: 'A face. A thousand stories.', image: '/artworks/pearl-earring.jpg', text: 'Presence & personality' },
  { category: 'Still life', title: 'Beauty in the everyday.', image: '/artworks/sunflowers.jpg', text: 'Small moments & golden details' }
];
const artists = [
  { name: 'Vincent van Gogh', years: '1853–1890', image: '/artworks/sunflowers.jpg', second: '/artworks/starry-night.jpg', summary: 'Expressive color, restless skies, and beauty found in ordinary things.' },
  { name: 'Claude Monet', years: '1840–1926', image: '/artworks/water-lily-pond.jpg', second: '/artworks/water-lily-pond.jpg', summary: 'Light and reflections, captured in a world of soft, shifting color.' },
  { name: 'Katsushika Hokusai', years: '1760–1849', image: '/artworks/great-wave.jpg', second: '/artworks/great-wave.jpg', summary: 'Bold lines and the quiet balance between people and the natural world.' }
];
const stories = [
  { title: 'Start with a color you love.', tag: 'The color edit', image: '/artworks/starry-night.jpg', time: '2 min read', paragraphs: ['Choosing art can start with a single color. Look for a shade that already feels at home in your room: a deep blue in a cushion, the green of a plant, or the warm ochre of afternoon light.', 'Try a print with that color as a starting point, then let its other tones introduce something unexpected. A blue painting can sit beautifully beside warm wood and off-white walls.', 'You do not need to match every detail. Leave room for a little contrast, and choose the painting you want to keep looking at.'] },
  { title: 'Build a wall that tells your story.', tag: 'At home with art', image: '/artworks/still-life-apples.jpg', time: '3 min read', paragraphs: ['Start with one piece you love, then add works that share a color, a mood, or a personal connection. A thoughtful gallery wall can mix portraits, landscapes, and still lifes.', 'Lay your arrangement on the floor first, or use paper templates on the wall. Keep the gaps consistent so different sizes feel intentional.', 'Give the collection room to grow. An empty space today can be the perfect home for tomorrow’s favorite.'] },
  { title: 'Let a little nature in.', tag: 'A slower perspective', image: '/artworks/water-lily-pond.jpg', time: '2 min read', paragraphs: ['A painted landscape offers a small change of pace. The open sky, the rhythm of water, or a vase of flowers can bring a sense of the outdoors into an everyday room.', 'Choose softer greens and blues for a quiet corner, or rich golden flowers when you want a warmer focal point.', 'Place the piece where you will notice it during a daily ritual: beside your reading chair, across from your desk, or near the table where you have your first cup of coffee.'] }
];
export function BrowseEdits({ onSelect }) {
  return <section className="edits-section container" id="edits"><div className="section-heading"><div><p className="eyebrow">Let your eye wander</p><h2>Find your kind of art.</h2></div><p>A mood, a moment, a new direction.<br />There is more than one way to begin.</p></div><div className="edits-grid">{edits.map(edit => <button className="edit-card" key={edit.category} onClick={() => onSelect(edit.category)}><div className="edit-image"><img src={edit.image} alt={`${edit.category} artwork selection`} loading="lazy" /><span>{artworks.filter(art => art.category === edit.category).length} works</span></div><div className="edit-copy"><p className="eyebrow">{edit.category}</p><h3>{edit.title}</h3><p>{edit.text}</p><span aria-hidden="true">↗</span></div></button>)}</div></section>;
}
export function ArtistSpotlights({ onSelect }) {
  return <section className="artists-section container" id="artists"><div className="section-heading"><div><p className="eyebrow">The people behind the paintings</p><h2>Meet a different perspective.</h2></div><p>Get to know an artist<br />through the work they leave behind.</p></div><div className="artists-grid">{artists.map(artist => <article key={artist.name} className="artist-feature"><button className="artist-feature-image" onClick={() => onSelect(artist.name)} aria-label={`Explore works by ${artist.name}`}><img src={artist.image} alt={`Featured artwork by ${artist.name}`} loading="lazy" /></button><div><span className="artist-years">{artist.years}</span><h3>{artist.name}</h3><p>{artist.summary}</p><button className="text-link" onClick={() => onSelect(artist.name)}>Explore the artist <span aria-hidden="true">↗</span></button></div></article>)}</div></section>;
}
export function Journal() {
  const [article, setArticle] = useState(null);
  return <><section className="journal-section container" id="journal"><div className="section-heading"><div><p className="eyebrow">Notes from the gallery</p><h2>A little inspiration.</h2></div><p>Fresh ideas for living with art.<br />Take a moment. Make it yours.</p></div><div className="journal-grid">{stories.map(story => <article className="journal-card" key={story.title}><button className="journal-image" onClick={() => setArticle(story)} aria-label={`Read ${story.title}`}><img src={story.image} alt={`Artwork illustrating ${story.tag.toLowerCase()}`} loading="lazy" /></button><div><p className="eyebrow">{story.tag}<span>{story.time}</span></p><h3><button onClick={() => setArticle(story)}>{story.title}</button></h3><button className="text-link" onClick={() => setArticle(story)}>Read the story <span aria-hidden="true">↗</span></button></div></article>)}</div></section>{article && <Modal titleId="journal-title" className="journal-modal" onClose={() => setArticle(null)}><img className="article-cover" src={article.image} alt={article.tag} /><div className="article-body"><p className="eyebrow">{article.tag} · {article.time}</p><h2 id="journal-title">{article.title}</h2>{article.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</div></Modal>}</>;
}
export function MembershipBanner({ user, onJoin }) {
  return <section className="membership container"><div className="membership-copy"><p className="eyebrow">Your personal collection</p><h2>{user ? 'Your favorites.\nAll in one place.' : 'An eye for art?\nYou belong here.'}</h2><p>{user ? 'Come back to the pieces that caught your eye. Your next favorite is waiting to be discovered.' : 'Save the pieces you love and build a collection that feels entirely your own.'}</p><button className="primary-button" onClick={onJoin}>{user ? 'Visit my account' : 'Create your free account'} <span aria-hidden="true">↗</span></button></div><div className="membership-art"><img src="/artworks/sunflowers.jpg" alt="Sunflowers by Vincent van Gogh" loading="lazy" /><img src="/artworks/still-life-apples.jpg" alt="Still Life with Apples by Paul Cézanne" loading="lazy" /></div></section>;
}
