import React from 'react';

const artworkImages = ['the-kiss', 'wheat-field', 'great-wave', 'pearl-earring', 'still-life-apples', 'sunflowers'];
const labels = { Landscapes: 'Landscape', Seascapes: 'Seascape', Portraits: 'Portrait', 'Still life': 'Still Life' };
export function LandingHero({ onBrowse, onSell }) {
  return <section className="landing-hero"><div className="container hero-layout"><div className="hero-copy"><p className="eyebrow">Original art. Real people.</p><h1>Discover<br />Extraordinary<br /><em>Art</em></h1><p className="hero-description">Buy and sell original paintings from talented artists. Support independent creators and bring meaningful art into your life.</p><div className="hero-buttons"><button className="primary-button" onClick={onBrowse}>Explore Art <span>→</span></button><button className="secondary-button" onClick={onSell}>Start Selling</button></div><div className="hero-values"><div><strong>Original</strong><span>One-of-a-kind works</span></div><div><strong>Independent</strong><span>Artists & collectors</span></div><div><strong>Connected</strong><span>Direct to the seller</span></div></div></div><span className="hero-caption">A little art. A world of your own.</span></div></section>;
}
export function CategoryStrip({ categories, selected, onSelect }) {
  return <section className="category-section container"><div className="section-heading"><div><h2>Browse by Category</h2><p>Find the perfect piece for your space</p></div><button className="text-link" onClick={() => onSelect('')}>View all →</button></div><div className="category-strip">{categories.map((category, i) => <button key={category} className={'category-tile ' + (selected === category ? 'selected' : '')} aria-pressed={selected === category} onClick={() => onSelect(category)}><img src={'/artworks/' + artworkImages[i] + '.jpg'} alt="" loading="lazy" /><span>{labels[category] || category}</span></button>)}</div></section>;
}
export function EditorialPanels({ onBrowse, onSell }) {
  return <><section className="editorial-panels container"><article className="editorial-panel buy-panel"><p className="eyebrow">Buy art</p><h2>Find Art That<br />Speaks to You</h2><p>Discover a piece that feels like home, from independent artists and collectors.</p><button className="primary-button" onClick={onBrowse}>Browse Collection →</button></article><article className="editorial-panel sell-panel"><p className="eyebrow">Sell art</p><h2>Share Your Vision<br />With the World</h2><p>Your art deserves to be seen. Set your price and connect with people who love it.</p><button className="primary-button" onClick={onSell}>Start Selling →</button></article></section><section className="about-section container" id="about"><div><p className="eyebrow">The art of connection</p><h2>Art connects people.</h2></div><p>Lumière brings original paintings and the people behind them together. Discover something that moves you, meet its owner, and make it part of your story.</p><div className="about-note"><span>01 / Discover</span><span>02 / Connect</span><span>03 / Collect</span></div></section></>;
}
